In [33]:
from PIL import Image
import pytesseract
import json

# Load the image
# image = Image.open('Screenshot 2023-10-25 154133.png')
image = Image.open('Screenshot 2023-10-25 142012.png')
# image = Image.open('result_image.jpg')
image = image.convert('L')
image = image.rotate(-90, expand=True)
image.show()
# 
# Rotate the image by 90 degrees (counter-clockwise) to make vertical text horizontal
# rotated_image = image.rotate(90, expand=True)

# Use OCR to extract text from the rotated image
extracted_text = pytesseract.image_to_string(image)

# Process the extracted text to create a JSON output (same as in the previous code)

data = {}

# Split the text into line
lines = extracted_text.split('\n')
lines

years = []

for l in lines : 
  if '-' in l: 
    years.append(l)

years = years[0].split(' ')

# Create a list to store individual years
individual_years = []

# Iterate through the original array
for year in years:
    # Split the year range by hyphen
    year_range = year.split('-')
    
    # If it's a single year, add it to the list
    if len(year_range) == 1:
        individual_years.append(year_range[0])
    else:
        # If it's a range, extract the start and end years
        start_year, end_year = map(int, year_range)
        
        # Add all years in the range to the list
        for year in range(start_year, end_year + 1):
            individual_years.append(str(year))

# The individual_years list now contains one year per string
print(individual_years)



# # Extract x-axis (years) and y-axis (keys and values)
# x_axis = lines[0].split()[1:]  # Assuming the years are on the first line
# y_data = {}
# for line in lines[1:]:
#     parts = line.split()
#     key = parts[0]  # Assuming the first word is the key
#     values = [int(value) for value in parts[1:]]  # Assuming the values start from the second word
#     y_data[key] = values

# # Create the JSON output (same as in the previous code)

# for year, values in zip(x_axis, zip(*y_data.values())):
#     data[year] = {key: value for key, value in zip(y_data.keys(), values)}

# # Save the JSON output to a file or return it as needed
# with open('output.json', 'w') as json_file:
#     json.dump(data, json_file, indent=4)

# # Print the JSON output
# print(json.dumps(data, indent=4))


['2013', '2014', '2015', '2016', '2017']


In [34]:
from PIL import Image
import pytesseract
import json

# Load the image
# image = Image.open('Screenshot 2023-10-25 154133.png')
image = Image.open('Screenshot 2023-10-25 140904.png')
# image = Image.open('result_image.jpg')
image = image.convert('L')
image = image.rotate(-90, expand=True)
image.show()
# 
# Rotate the image by 90 degrees (counter-clockwise) to make vertical text horizontal
# rotated_image = image.rotate(90, expand=True)

# Use OCR to extract text from the rotated image
extracted_text = pytesseract.image_to_string(image)

# Process the extracted text to create a JSON output (same as in the previous code)

data = {}

# Split the text into line
lines = extracted_text.split('\n')
lines

# years = []

# for l in lines : 
#   if '-' in l: 
#     years.append(l)

# years = years[0].split(' ')

# # Create a list to store individual years
# individual_years = []

# # Iterate through the original array
# for year in years:
#     # Split the year range by hyphen
#     year_range = year.split('-')
    
#     # If it's a single year, add it to the list
#     if len(year_range) == 1:
#         individual_years.append(year_range[0])
#     else:
#         # If it's a range, extract the start and end years
#         start_year, end_year = map(int, year_range)
        
#         # Add all years in the range to the list
#         for year in range(start_year, end_year + 1):
#             individual_years.append(str(year))

# # The individual_years list now contains one year per string
# print(individual_years)



# # Extract x-axis (years) and y-axis (keys and values)
# x_axis = lines[0].split()[1:]  # Assuming the years are on the first line
# y_data = {}
# for line in lines[1:]:
#     parts = line.split()
#     key = parts[0]  # Assuming the first word is the key
#     values = [int(value) for value in parts[1:]]  # Assuming the values start from the second word
#     y_data[key] = values

# # Create the JSON output (same as in the previous code)

# for year, values in zip(x_axis, zip(*y_data.values())):
#     data[year] = {key: value for key, value in zip(y_data.keys(), values)}

# # Save the JSON output to a file or return it as needed
# with open('output.json', 'w') as json_file:
#     json.dump(data, json_file, indent=4)

# # Print the JSON output
# print(json.dumps(data, indent=4))


['BUILDING ENERGY CONSUMPTION',
 '',
 'MWh',
 '100000',
 '',
 '‘80000',
 '',
 '65,374',
 '',
 '‘60000',
 '',
 '70,710',
 '91',
 '',
 '‘40000',
 '',
 '20000',
 '',
 '24,43',
 '',
 '0 2',
 '',
 '2013 2014-2015 2016-2017',
 '',
 'Mi Retail Il Mixed Developments',
 '']

In [35]:
import cv2
import numpy as np

# Load the image
image = cv2.imread('Screenshot 2023-10-25 154133.png')

# Convert the image to grayscale (if not already)
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Apply thresholding
_, thresholded_image = cv2.threshold(gray_image, 200, 255, cv2.THRESH_BINARY)

# Invert the thresholded image
inverted_image = cv2.bitwise_not(thresholded_image)

# Create an all-black background image with the same size
black_background = np.zeros_like(image)

# Copy the original image onto the black background using the inverted mask
result_image = cv2.bitwise_and(image, image, mask=inverted_image)

# # Display or save the result image
cv2.imshow('Result Image', result_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Save the result image
cv2.imwrite('result_image.jpg', result_image)


True

In [36]:
from PIL import Image
import pytesseract
import json

# Load the image
# image = Image.open('Screenshot 2023-10-25 154133.png')
image = Image.open('Screenshot 2023-10-25 154133.png')
# image = Image.open('result_image.jpg')
image = image.convert('L')
image = image.rotate(-90, expand=True)
image.show()
# 
# Rotate the image by 90 degrees (counter-clockwise) to make vertical text horizontal
# rotated_image = image.rotate(90, expand=True)

# Use OCR to extract text from the rotated image
extracted_text = pytesseract.image_to_string(image)

# Process the extracted text to create a JSON output (same as in the previous code)

data = {}

# Split the text into line
lines = extracted_text.split('\n')
lines





# # Extract x-axis (years) and y-axis (keys and values)
# x_axis = lines[0].split()[1:]  # Assuming the years are on the first line
# y_data = {}
# for line in lines[1:]:
#     parts = line.split()
#     key = parts[0]  # Assuming the first word is the key
#     values = [int(value) for value in parts[1:]]  # Assuming the values start from the second word
#     y_data[key] = values

# # Create the JSON output (same as in the previous code)

# for year, values in zip(x_axis, zip(*y_data.values())):
#     data[year] = {key: value for key, value in zip(y_data.keys(), values)}

# # Save the JSON output to a file or return it as needed
# with open('output.json', 'w') as json_file:
#     json.dump(data, json_file, indent=4)

# # Print the JSON output
# print(json.dumps(data, indent=4))


['26,754 64,965', '']

In [37]:
import cv2
import numpy as np

# Load the image
image = cv2.imread('result_image.jpg')

# Create a sharpening kernel
sharpening_kernel = np.array([[-1, -1, -1],
                              [-1, 9, -1],
                              [-1, -1, -1]])

# Apply the sharpening filter to the image
sharpened_image = cv2.filter2D(image, -1, sharpening_kernel)

# Display or save the sharpened image
cv2.imshow('Sharpened Image', sharpened_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Save the sharpened image
cv2.imwrite('sharpened_image.jpg', sharpened_image)


True

In [38]:
import cv2
import numpy as np

# Load the image
image = cv2.imread('Screenshot 2023-10-25 154133.png')

# Convert the image to grayscale
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Threshold the image to create a binary mask for white areas
_, white_mask = cv2.threshold(gray_image, 200, 255, cv2.THRESH_BINARY)

# Invert the binary mask to create a black mask
black_mask = cv2.bitwise_not(white_mask)

# Set the color you want for the text (black in this case)
black_color = (0, 0, 0)

# Apply the color to the original image using the black mask
image_with_black_text = cv2.addWeighted(image, 1, cv2.cvtColor(black_mask, cv2.COLOR_GRAY2BGR), 0, 0)

# Display or save the image with black text
cv2.imshow('Image with Black Text', image_with_black_text)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Save the image with black text
cv2.imwrite('image_with_black_text.jpg', image_with_black_text)


True

In [39]:
import cv2
import numpy as np

# Load the image
image = cv2.imread('Screenshot 2023-10-25 140904.png')

# Convert the image to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Apply Gaussian blur to reduce noise
blurred = cv2.GaussianBlur(gray, (5, 5), 0)

# Detect edges using the Canny edge detector
edges = cv2.Canny(blurred, 50, 150, apertureSize=3)

# Find contours in the edges
contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Filter for rectangles by checking the number of vertices
rectangles = []
for contour in contours:
    perimeter = cv2.arcLength(contour, True)
    vertices = cv2.approxPolyDP(contour, 0.04 * perimeter, True)
    if len(vertices) == 4:
        rectangles.append(vertices)

# Draw and save each rectangle as a separate image
for i, rect in enumerate(rectangles):
    # Create a mask for the current rectangle
    mask = np.zeros_like(image)
    cv2.drawContours(mask, [rect], -1, (255, 255, 255), thickness=cv2.FILLED)

    # Bitwise-AND to extract the rectangle
    result = cv2.bitwise_and(image, mask)

    # Save the rectangle as a separate image
    cv2.imwrite(f'rectangle_{i}.jpg', result)

# Display or save the image with rectangles highlighted
cv2.drawContours(image, rectangles, -1, (0, 255, 0), 2)
cv2.imshow('Image with Rectangles', image)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [40]:
import cv2
import numpy as np

# Load the image
image = cv2.imread('Screenshot 2023-10-25 140904.png')

# Convert the image to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Apply Gaussian blur to reduce noise
blurred = cv2.GaussianBlur(gray, (5, 5), 0)

# Detect edges using the Canny edge detector
edges = cv2.Canny(blurred, 50, 150, apertureSize=3)

# Find contours in the edges
contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

contours 

# Filter for contours representing bars
# bar_contours = []
# for contour in contours:
#     x, y, w, h = cv2.boundingRect(contour)
#     aspect_ratio = w / h
#     if aspect_ratio > 2:  # Adjust this threshold based on your graph
#         bar_contours.append(contour)

# # Draw and save the bars as separate images
# for i, contour in enumerate(bar_contours):
#     x, y, w, h = cv2.boundingRect(contour)
#     bar = image[y:y+h, x:x+w]
#     cv2.imwrite(f'bar_{i}.jpg', bar)


(array([[[229, 414]],
 
        [[229, 417]],
 
        [[228, 418]],
 
        [[226, 418]],
 
        [[225, 419]],
 
        [[220, 419]],
 
        [[219, 418]],
 
        [[219, 417]],
 
        [[218, 418]],
 
        [[216, 418]],
 
        [[215, 419]],
 
        [[212, 419]],
 
        [[211, 418]],
 
        [[211, 417]],
 
        [[211, 419]],
 
        [[216, 419]],
 
        [[217, 418]],
 
        [[218, 418]],
 
        [[219, 419]],
 
        [[218, 420]],
 
        [[218, 421]],
 
        [[219, 422]],
 
        [[221, 422]],
 
        [[221, 420]],
 
        [[222, 419]],
 
        [[225, 419]],
 
        [[226, 418]],
 
        [[229, 418]]], dtype=int32),
 array([[[221, 414]],
 
        [[221, 416]],
 
        [[222, 417]],
 
        [[223, 416]],
 
        [[224, 416]],
 
        [[224, 414]]], dtype=int32),
 array([[[213, 414]],
 
        [[213, 416]],
 
        [[214, 417]],
 
        [[215, 416]],
 
        [[215, 414]]], dtype=int32),
 array([[[146, 414]],
 
 